### ISSUE TITLE
holo plugin API v3

### ISSUE THREAD

**Issue by majewsky** [holocm/holo#12]
Centralize a lot of stuff that is redundant between plugins:
- [x] move API version compatibility check from plugins into frontend, have plugins report a range of compatible API versions (min..max) with an `info` command
- [x] move diff generation into the frontend (plugins have to give two filenames on stdout, separated by NUL; recommend usage of HOLO_CACHE_DIR for non-file entities)
- [X] add new command messages `needs-force-to-{modify,restore}` to FD 3 of the `apply` command that indicates the common `has been {changed,deleted}" by user, use --force to {overwrite,restore}` error (only the frontend will show this error, then; later
  - [x] extend the frontend with an option to display a diff automatically when that happens
- [x] adjust external plugins to the new API version:
  - [x] holo-run-scripts
  - [x] holo-ssh-keys
  - [x] holo-users-groups
