### ISSUE TITLE
checklist for v3.0

### ISSUE THREAD

**Issue by majewsky** [holocm/holo#53]
The last release was over three years ago, so we have a bit of ecosystem evolution to catch up to:

- [x] switch from golangvend to go.mod
- [x] switch from Travis CI to GitHub Actions
- [x] ~~check if we can get rid of gocovcat ([Go 1.10 can generate coverprofiles for multiple packages at once](https://github.com/golang/go/issues/6909))~~ We have at least one testcase (the one with the ALPM hook where we absolutely have to run the test binary manually.

Followup issues from adding generators:

- [x] `holo scan` as non-privileged fails because regular files copied from `/usr/share/holo` cannot have all their original permissions applied by a non-privileged user

Also, some more things I want to do for v3.0 that I don't feel like opening separate issues for:

- [x] add CLI selectors for generators (e.g. `holo apply /usr/share/holo/generators/foo.sh` applies all entities with source files produced by that generator)
- [x] double-check shell completions (zsh completion looks broken for me right now)
- [x] add `holo selectors` to simplify shell completion implementations
- [x] do not litter `/tmp/holo-ssh-keyNNN` files
- [x] merge #46 (or at least the parts that still apply)

After the release:

- [x] refresh the website: proofread and update for new features where necessary
- [x] include the manpages in the website
- [x] ~~render manpages from Markdown instead of POD~~ (I wanted to make my life easier by going with a more common format, but Markdown is not expressive enough to make nice manpages out of it. I'd rather write a POD parser for the website than try to shoehorn custom syntax into Markdown.)
- [x] update the Pacman repo
- [ ] bring the Debian repo back in shape
- [ ] do a "Show HN"
